### ISSUE TITLE
Microsoft Login 404

### ISSUE THREAD

**Issue by myblueyoshi64** [craftycodie/MineOnline#267]
when i put in my Microsoft email
and put in the correct password it says it is wrong
i put it in a second time it appears to load 
but then says on a white background in the top corner "not found"
![Capture](https://user-images.githubusercontent.com/78583340/107911036-c6311f00-6faf-11eb-824c-287302d5c0e8.PNG)

--- Edited by @codieradical 8/3/21 ---
- Removed an image due to privacy concerns.

**Comment by codieradical** [comment]
That's a new one, unfortunately I can't really debug it as I don't have a Microsoft account.
