### ISSUE TITLE
No connection to BetaWorld 2.0

### ISSUE THREAD

**Issue by syneekis415** [craftycodie/MineOnline#298]
![noConnection](https://user-images.githubusercontent.com/80713560/128638347-50bab0c2-2a00-4655-9d20-521a0ade5040.png)

Some servers say no connection. but theyre online and there is connection if you use normal minecraft laucher
if you join serer it says "Failed to connect server" "Conenction refused: connect"

Laucnher trys to conenct: 93.104.209.63:25565
but thats old address BW2 is nowdays under adress: 95.216.168.172:25565 aka betaworld.xyz

player count icon dec text still works but conenctign server does not. in plugin settings server address is set to "betaworld.xyz"

**Comment by GameHerobrine** [comment]
betaworld can be down sometimes

**Comment by craftycodie** [comment]
This is an issue on betaworld's end, i don't host the server list anymore and it's down to them to list their server correctly.
