### ISSUE TITLE
[BUG] MSA login has entirely stopped working.

### ISSUE THREAD

**Issue by MisterSheeple** [craftycodie/MineOnline#321]
**Describe the bug**
When logging in via both Microsoft and GitHub accounts, the following error is given: "Microsoft account is unavailable from this site, so you can't sign in or sign up. The site may be experiencing a problem. You can sign in or sign up at other Microsoft sites and services, or try again later at this site."

**To Reproduce**
1. Go to login screen.
2. Click "Login via Microsoft"
3. Sign in.
4. See error.

**Expected behavior**
MSA properly authenticates with the launcher and no error is given.

**Screenshots**

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Windows 11 (yes, I know :/)
 - Java Version: Oracle JRE 1.8.0_251
 - MineOnline Version: 4.7.4, 4.7.0, 4.5.3 (I was previously able to use MSA on 4.5.3, but this is no longer the case, so this isn't something broken by a recent update)
 - Minecraft Version: N/A

**Additional context**
Nothing else.

**Comment by craftycodie** [comment]
Cannot reproduce. Please provide a log file (%AppData%\.mineonline\latest.log)

**Comment by MisterSheeple** [comment]
> 

Logs look normal apart from this error:

> java.io.FileNotFoundException: C:\Users\User\AppData\Roaming\.mineonline\cache\lastlogin (The system cannot find the file specified)
>	at java.io.FileInputStream.open0(Native Method)
>	at java.io.FileInputStream.open(Unknown Source)
>	at java.io.FileInputStream.<init>(Unknown Source)
>	at gg.codie.mineonline.utils.LastLogin.readLastLogin(LastLogin.java:67)
>	at gg.codie.mineonline.gui.MenuManager.main(MenuManager.java:154)

I'm not sure if this could be related to MSA login not working, but it's the only thing that's out of the ordinary in here.

**Comment by craftycodie** [comment]
>  If it's always going to be like this, perhaps MSA login would have to be entirely moved away from using JavaFX, similar to what Betacraft has done in its latest updates.

I'm convinced. I'll get around to it.

**Comment by MisterSheeple** [comment]
Thank you. Just an fyi by the way, Mojang has just announced today that Mojang account logins will be entirely disabled as of March 10, and from then on, you can only use Minecraft with a Microsoft account. This will probably make the need for working MSA authentication more important for MineOnline users.

**Comment by craftycodie** [comment]
Hi @MisterSheeple 
please give the latest test build (4.8.0-tb1) a go :)

**Comment by MisterSheeple** [comment]
Alright I'll give it a shot, thanks!

**Comment by MisterSheeple** [comment]
Everything seems to be working so I'll go ahead and close this. Thanks!
