### ISSUE TITLE
[BUG] Missing door/explosion sounds in beta versions (Linux)

### ISSUE THREAD

**Issue by rockrevenchy** [craftycodie/MineOnline#323]
Please check the [Known Issues](https://github.com/craftycodie/MineOnline/discussions/300) page before reporting a bug!

**Describe the bug**
Might seem like a stupid thing but it seems the door opening/closing sound is missing from beta 1.0.0 all the way to release 1.1

**To Reproduce**
1- play any beta version
2- open or close a door

**Expected behavior**
The door should do this sound
https://www.youtube.com/watch?v=u-tQhdaXd80

**Screenshots**
(not applicable)

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Ubuntu 21.04
 - Java Version 1.8.0_281
 - MineOnline Version 4.7.2
 - Minecraft Version Any beta version

**Additional context**
Every other sounds works just fine, just missing the door one as far as I noticed

**Comment by rockrevenchy** [comment]
The same seems to apply for creeper explosions

**Comment by craftycodie** [comment]
Hi @rockrevenchy, thanks for the report.
Unfortunately I am unable to reproduce this issue.

Could you please check that sounds have been properly downloaded. They should be present at:
<home directory>\.mineonline\resources\<beta version>\newsound\random

In addition, could you please provide your log file, located at
<home directory>\.mineonline\latest.log

Thank you.

**Comment by rockrevenchy** [comment]
Hi, I can confirm the sound files are indeed present however I stumbled upon something interesting while looking into latest.log as you requested.

The sound files which makes no noises appears in those logs with this error messages.
`java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/random/door_close.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.URL.openStream(URL.java:1067)
	at bz.a(SourceFile:104)
	at bz.a(SourceFile:93)
	at bz.run(SourceFile:42)`

The same error pops for bow.ogg, door_open.ogg and explode.ogg

here is the complete log after starting and loading a world in beta 1.3_01

https://pastebin.com/bfueHm7R

**Comment by craftycodie** [comment]
That is very bizzare, and the source of the problem.
I'll have a dig, cheers!

**Comment by craftycodie** [comment]
In case you're curious here's a bit of an explaination of the issue:
Because Minecraft used to be played in browser, sounds would be downloaded as the game runs, and cached.
These days, the launcher downloads the sounds for a given minecraft version.
To fix sound with old versions, I've intercepted calls that would download & cache the sounds. I've moved the cache to the folder you checked, so that I can keep different files for different minecraft versions to maintain an authentic experience of old versions. As for the download requests, I wrote a custom HTTP protocol which should intercept the old download requests. It seems that I'm not fully intercepting this request which is causing the issue.

**Comment by craftycodie** [comment]
Hi again @rockrevenchy 
I think I might have fixed the issue, I've compiled a test build for you to try
https://ci.appveyor.com/api/buildjobs/s944prai5850i1q9/artifacts/target%2FMineOnline-bugfix%23323-Dev.jar
Please delete the `~/mineonline/resources/b1.3_01/` folder before testing.
Thanks!

**Comment by rockrevenchy** [comment]
sure thing, sorry was out for the last hour haha

I deleted the ~/mineonline/resources/b1.3_01/ to be sure and tried it again, unfortunately it doesnt seems to change the final result.

(I proceeded to delete the resource folder as a whole and load a second time to no avail)

Here is the pastebin of the latest.log

https://pastebin.com/nT7ifVuc


(Btw thx a lot for checking this out ;p love your work)

**Comment by craftycodie** [comment]
Funky, well in that case I'm not sure what's causing the issue, but I think I can implement a workaround.
If this doesn't work, I'm out of ideas 🤷‍♀️

https://ci.appveyor.com/api/buildjobs/fru6l8vngoneshjd/artifacts/target%2FMineOnline-bugfix%23323-Dev.jar

**Comment by rockrevenchy** [comment]
Ohhh that version does work flawlessly

**Comment by craftycodie** [comment]
Very cool, will release, thanks for your help!

**Comment by rockrevenchy** [comment]
Hey no problem, thx for your time and patience!
