### ISSUE TITLE
[BUG] MSA 2-step verification not working at all (password works)

### ISSUE THREAD

**Issue by mariobot128** [craftycodie/MineOnline#327]
**Describe the bug**
Microsoft Athentification 2-step verification doesn't work after email and code : white windows with empty button

**To Reproduce**

1. Log in with ms
2. click on e-mail <e-mail address>
3. enter the code
4. see error

**Expected behavior**
Log in successful, window closed and back to luancher while logged in with ms account

**Screenshots**
![image](https://user-images.githubusercontent.com/99540470/153712144-0236775f-e1dd-40c3-83e3-483c1b607cca.png)

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Windows 10 Version 21H2 build 19044.1526
 - Java Version: Version 8 update 3 (build 1.8.0_311-b11
 - MineOnline Version 4.7.5 (currently the latest)

**Additional context**
i have 2-step verification on my ms account.

**Comment by craftycodie** [comment]
Hi @mariobot128 
please give the latest test build (4.8.0-tb1) a go :)
