### ISSUE TITLE
[BUG] Issue with skins

### ISSUE THREAD

**Issue by DelofJ** [craftycodie/MineOnline#332]
**Describe the bug**
The skin isn't properly converted when you have a skin with the Alex format and the 64x64 pixels format

**To Reproduce**
1. Have  a skin with the Alex format and the 64x64 pixels format
2. Launch Minecraft 1.1
3. Press F5 to see your skin

**Screenshots**
![2022-07-09_22 26 06](https://user-images.githubusercontent.com/50058956/178121518-fc5331f7-d707-462a-b63f-2211db9bf97b.png)

**Expected behavior**
The skin would be properly converted

**Desktop (please complete the following information):**
 - Windows 10 21H2
 - Java 1.8.0_333
 - MineOnline 4.7.5
 - Minecraft Version : all

**Comment by DelofJ** [comment]
I made a Pull Request that fixes this bug https://github.com/craftycodie/MineOnline/pull/331

**Comment by craftycodie** [comment]
Please provide example skins.

**Comment by DelofJ** [comment]
Here is a (dumb) test skin with how it is in 1.16.5
![2022-07-23_21 53 28](https://user-images.githubusercontent.com/50058956/180620904-7fc9e805-21f7-4eb1-ae4c-386067170c47.png)
And this is what the skin is in MineOnline
![2022-07-23_21 44 10](https://user-images.githubusercontent.com/50058956/180620929-cf443be6-752e-4898-b17c-2e9719f3db0b.png)
The skin is converted incorrectly
