### ISSUE TITLE
[BUG] MacOS screen size 

### ISSUE THREAD

**Issue by Spritzerland** [craftycodie/MineOnline#337]
Please check the [Known Issues](https://github.com/craftycodie/MineOnline/discussions/300) page before reporting a bug!

When launching the .jar, the screen size of the game is not matched with the game window. This messes with mouse pos.

1. Open .jar file
2. Screen will be misaligned

Screen size same as window

If you're not sure, go to the About screen in the launcher/game.
 - OS: MacOS
 - Java Version 8
 - MineOnline Version: Latest
 - Minecraft Version: Launcher

**Comment by craftycodie** [comment]
I've seen this one before I think. If you resize the window, does it correct itself?

**Comment by craftycodie** [comment]
Unable to reproduce, recommend using zulu java 8 through rosetta.
