### ISSUE TITLE
When I open the .jar nothing happens

### ISSUE THREAD

**Issue by Durbie** [craftycodie/MineOnline#339]
**Describe the bug**

**To Reproduce**
1. Open the .jar

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: [MacOS Ventura]
 - Java Version [8 Update 351]
 - MineOnline Version [4.8.2]
 
I also gave the file permission to run.

**Comment by craftycodie** [comment]
I need more information, are you seeing any error messages? Are you running through Rosetta or Native?

**Comment by Durbie** [comment]
No error messages, I am using Native. I just run the .jar and nothing opens, I check activity monitor and java isn't running in the background.

**Comment by craftycodie** [comment]
Please use Rosetta instead, x86 JVMs are more reliable currently.

**Comment by craftycodie** [comment]
Which Minecraft version are you trying to launch?

**Comment by Durbie** [comment]
Wdym? I have the jar on my desktop. I can't even run a version

**Comment by craftycodie** [comment]
You may have to allow opening the jar under Privacy & Security settings.
