### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mariobot128** [craftycodie/MineOnline#341]
the blue and red color are inverted on beta 1.7.3

1. go to singleplayer or multiplayer
2. launch beta 1.7.3

**expected behavior**
they're not supposed to be inverted

**Screenshots**
![image](https://user-images.githubusercontent.com/99540470/208256270-72e0a544-526d-4e7b-bda1-50cccdd33334.png)
![image](https://user-images.githubusercontent.com/99540470/208256278-01f94043-818e-419f-a5f8-d26d2f60c6d8.png)
![image](https://user-images.githubusercontent.com/99540470/208256301-7c954879-e51e-40e3-8fdc-5f10eabb6c64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 22H2 (OS Build 19045.2364)
 - Java Version 8u315 (build 1.8.0_351-b10)
 - MineOnline Version 4.8.6
 - Minecraft Version beta 1.7.3

**Comment by craftycodie** [comment]
Hey @mariobot128 , thanks for the report! For now use 4.8.2, I'll fix this issue today.

**Comment by craftycodie** [comment]
Should be fixed, please grab the latest update and reopen if the issue persists. Thanks for the report!
