### ISSUE TITLE
[BUG] Cannot Enter Full Screen

### ISSUE THREAD

**Issue by jcurtis06** [craftycodie/MineOnline#342]
**Describe the bug**
Full screen doesn't work (mostly)

**To Reproduce**
1. Open up a version of Minecraft. This occurred on beta 1.6 & 1.9 for me.
2. Attempt to resize the window.
3. The button to maximize the window on mac is grayed out

**Expected behavior**
Game should be resizable

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Mac OS X (M1)
 - Java Version 1.8.0_352
 - MineOnline Version 4.8.8
 - Minecraft Version Beta 1.6/1.9

**Additional context**
I also tried using Option + F11 to maximize. This *somewhat* worked, however, it shrunk the window into the bottom left corner of my screen and turned all blank space blue. Also, when using this mode, the red & blue color glitches appear. I tried this on both the built in laptop screen & my external monitor.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/77545656/210100695-4e79a1cc-49ab-4172-a594-39dbb7896c20.png">

**Comment by craftycodie** [comment]
Is your JVM under rosetta or native?

**Comment by jcurtis06** [comment]
Not entirely sure. I’m pretty sure it’s running native? I’m using the Azulu distribution

**Comment by jcurtis06** [comment]
Alright, so I switched to running the jVM under rosetta. I can now resize the window, but I cannot enter borderless.
